// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7b4f6317-321c-4d80-b451-75df30752c6e";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSchedulerADurationMinutesChange();
void onSchedulerARepeatIntervalChange();
void onSchedulerARepeatTypeChange();
void onSchedulerBDurationMinutesChange();
void onSchedulerBRepeatIntervalChange();
void onSchedulerBRepeatTypeChange();
void onSchedulerHDurationMinutesChange();
void onSchedulerHRepeatIntervalChange();
void onSchedulerHRepeatTypeChange();
void onSchedulerStartMonthChange();
void onSchedulerStartYearChange();
void onStartAHourSchedChange();
void onStartAMinuteSchedChange();
void onStartBHourSchedChange();
void onStartBMinuteSchedChange();
void onStartHHourSchedChange();
void onStartHMinuteSchedChange();
void onSchedulerAEnabledChange();
void onSchedulerBEnabledChange();
void onSchedulerHEnabledChange();
void onSolenoidAManualControlChange();
void onSolenoidBManualControlChange();
void onSolenoidHManualControlChange();

float battery_voltage;
float humidity;
float tds_ppm;
float Temp;
float UltrasonicSensor;
float water_temperature;
int scheduler_A_durationMinutes;
int scheduler_A_repeatInterval;
int scheduler_A_repeatType;
int scheduler_B_durationMinutes;
int scheduler_B_repeatInterval;
int scheduler_B_repeatType;
int scheduler_H_durationMinutes;
int scheduler_H_repeatInterval;
int scheduler_H_repeatType;
int scheduler_start_month;
int scheduler_start_year;
int start_A_hour_sched;
int start_A_minute_sched;
int start_B_hour_sched;
int start_B_minute_sched;
int start_H_hour_sched;
int start_H_minute_sched;
bool scheduler_A_enabled;
bool scheduler_B_enabled;
bool scheduler_H_enabled;
bool soilMoisture;
bool solenoid_A_manual_control;
bool solenoid_B_manual_control;
bool solenoid_H_manual_control;
bool state_led_A;
bool state_led_B;
bool state_led_H;
bool water_level_safe;
CloudTime timePicker;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(battery_voltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tds_ppm, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(Temp, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(UltrasonicSensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_temperature, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(scheduler_A_durationMinutes, READWRITE, ON_CHANGE, onSchedulerADurationMinutesChange);
  ArduinoCloud.addProperty(scheduler_A_repeatInterval, READWRITE, ON_CHANGE, onSchedulerARepeatIntervalChange);
  ArduinoCloud.addProperty(scheduler_A_repeatType, READWRITE, ON_CHANGE, onSchedulerARepeatTypeChange);
  ArduinoCloud.addProperty(scheduler_B_durationMinutes, READWRITE, ON_CHANGE, onSchedulerBDurationMinutesChange);
  ArduinoCloud.addProperty(scheduler_B_repeatInterval, READWRITE, ON_CHANGE, onSchedulerBRepeatIntervalChange);
  ArduinoCloud.addProperty(scheduler_B_repeatType, READWRITE, ON_CHANGE, onSchedulerBRepeatTypeChange);
  ArduinoCloud.addProperty(scheduler_H_durationMinutes, READWRITE, ON_CHANGE, onSchedulerHDurationMinutesChange);
  ArduinoCloud.addProperty(scheduler_H_repeatInterval, READWRITE, ON_CHANGE, onSchedulerHRepeatIntervalChange);
  ArduinoCloud.addProperty(scheduler_H_repeatType, READWRITE, ON_CHANGE, onSchedulerHRepeatTypeChange);
  ArduinoCloud.addProperty(scheduler_start_month, READWRITE, ON_CHANGE, onSchedulerStartMonthChange);
  ArduinoCloud.addProperty(scheduler_start_year, READWRITE, ON_CHANGE, onSchedulerStartYearChange);
  ArduinoCloud.addProperty(start_A_hour_sched, READWRITE, ON_CHANGE, onStartAHourSchedChange);
  ArduinoCloud.addProperty(start_A_minute_sched, READWRITE, ON_CHANGE, onStartAMinuteSchedChange);
  ArduinoCloud.addProperty(start_B_hour_sched, READWRITE, ON_CHANGE, onStartBHourSchedChange);
  ArduinoCloud.addProperty(start_B_minute_sched, READWRITE, ON_CHANGE, onStartBMinuteSchedChange);
  ArduinoCloud.addProperty(start_H_hour_sched, READWRITE, ON_CHANGE, onStartHHourSchedChange);
  ArduinoCloud.addProperty(start_H_minute_sched, READWRITE, ON_CHANGE, onStartHMinuteSchedChange);
  ArduinoCloud.addProperty(scheduler_A_enabled, READWRITE, ON_CHANGE, onSchedulerAEnabledChange);
  ArduinoCloud.addProperty(scheduler_B_enabled, READWRITE, ON_CHANGE, onSchedulerBEnabledChange);
  ArduinoCloud.addProperty(scheduler_H_enabled, READWRITE, ON_CHANGE, onSchedulerHEnabledChange);
  ArduinoCloud.addProperty(soilMoisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(solenoid_A_manual_control, READWRITE, ON_CHANGE, onSolenoidAManualControlChange);
  ArduinoCloud.addProperty(solenoid_B_manual_control, READWRITE, ON_CHANGE, onSolenoidBManualControlChange);
  ArduinoCloud.addProperty(solenoid_H_manual_control, READWRITE, ON_CHANGE, onSolenoidHManualControlChange);
  ArduinoCloud.addProperty(state_led_A, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(state_led_B, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(state_led_H, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_level_safe, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timePicker, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
